### ISSUE TITLE
W2UI and Spring MVC

### ISSUE THREAD

**Issue by rcpacheco** [vitmalina/w2ui#1105]
Given the fact that SpringMVC offers the possibility to map the the request body directly to a Java object, it would be is very convenient if there could be a setting option to use as ajaxOptions.data in a POST the stringified version of the postData, that is the ajaxOptions.data.record instead of the ajaxOptions.data that follows the (cmd,recid,record) convention. Also, adding the charset to the contentType would be very usefull:

    ajaxOptions.data        = JSON.stringify(ajaxOptions.data.record);
    ajaxOptions.contentType = 'application/json; charset=UTF-8';

When responding from a controller, the easiest way to respond, when everything goes OK is to return an object and SpringMVC converts it automatically to a json object. In that case the status is still success and does not make sense to add a success property to the object. In that case it would be very convenient if the call back could called if the data.status or status are success: 

    if ((status == 'success' || data.status == 'success') && typeof callBack == 'function') callBack(data);

In the case of an error, there is no problem following your (status, message) object convention using an ExceptionHandler controller that returns such an object.

**Comment by vitmalina** [comment]
Appreciate your comment and I think I have a solution for you. You can set 
```js
w2utils.settings.dataType = 'JSON';
```
somewhere before you render grid and then it would submit all requests as request body (grid, forms, select fields). It will submit proper contentType too. See http://w2ui.com/web/docs/w2utils.settings

In current master I have also added option 'HTTPJSON', which will submit stringified JSON in a post. I personally do no like submissions in body, as it is harder to test these requests.

As for second problem. You can write a global converted that would process response from any ajax call and modify it before grid/form/etc. gets it. See jQuery.ajaxSetup for this. Then you can translate any error codes from the server and process errors in your way. Since grid/form/etc. uses jQuery.ajax, after you set it up, there is no need to do anything in grid, form, etc.

I hope it helps. Please close this request if it resolves your issues.

**Comment by rcpacheco** [comment]
Thanks for your advice an sorry for the late response. Indeed I'm using dataType = 'JSON', that is necessary. My problem was that even when using that dataType, the post will look like this:
```json
{"cmd":"save-record","recid":0,"record":{"first_name":"Ricardo","last_name":"Pacheco"}}
```
But  it is convenient to post something like this:
```json
{"first_name":"Ricardo","last_name":"Pacheco"}
```
But while reviewing your recomendation I came up with this solution:

```javascript
$.ajaxPrefilter(function( options, originalOptions, jqXHR ) {
                if(options.type === "POST") {
                    var data = JSON.parse(options.data);
                    if (data.cmd && data.cmd === "save-record") {
                        options.data = JSON.stringify(data.record);
                    };
                }
            });
```

I think that may be a useful to add it as a tip, somewhere in the docs, for some other users with a similar problem.
