### ISSUE TITLE
Date Search Bug in Grid v1.4 + (Git Master as well)

### ISSUE THREAD

**Issue by CBTyrone** [vitmalina/w2ui#1164]
The bug is found when searching date fields with the 'between' selector. I've tried configuring w2ui with various date formats as well as loading different date formats, but at no time does it select anything. Other selectors such as 'is', 'after, and 'before' appear to work correctly with my data.

I have tested that empty column data is not the source of the problem, and they are properly formatted.

Field configuration snippet --- type: 'date', size: '30%', sortable: true, resizable: true , format: 'yyyy/mm/dd'},

Search includes the same type and format information.

I have noted that the search box uses a different format of m/d/yyyy , however I would hope that it is able to convert dates to a general format for comparison. (I do notice that it won't sort according to the date value, but the format's alpha-numeric precedence).

Thanks!

**Comment by mrg2001** [comment]
The best way to work with dates is representing it in unix time (or timestamp). Then it is a number of milliseconds since 1970. Once you returned data as such, you can defined render: "date" or specify your own render function and then all is peachy. Search fields will work well with it too. Please see if this helps and close this issue.

**Comment by mpf82** [comment]
Closing issue: no response
