### ISSUE TITLE
list preselect first item

### ISSUE THREAD

**Issue by geods3** [vitmalina/w2ui#1219]
Hello, i need in listbox to preselect the first item,

i saw that in code is an option that says preselect first item and the default value is -1.

Is it easy to set this to 0 or to make an option that if it is set then select the index number that i have set in option , if not then take the default value (-1)?

**Comment by mpf82** [comment]
Simply set options.selected to whatever object in your items array you want to be pre-selected.

see http://w2ui.com/web/docs/form/fields-list

**Comment by geods3** [comment]
Maybe you didn't understand what i mean . I want to preselect the first item of the list every time the list search and return results

**Comment by samoilis** [comment]
I think this is a bug because the **w2field** prototype has the following lines of code:

```
// preselect first item
   options.index = -1;
   while (options.items[options.index] && options.items[options.index].hidden) options.index++;
   if (shown <= 0) options.index = -1;
```

The 

> options.index=-1

 do not preselect first item

I think it should be replaced with: options.index=0

When you have data entry forms that the speed is a very important thing I believe that the preselect item from the all of the lists (combo-enum-list) it should exist by default

**Comment by mrg2001** [comment]
You can add onLoad event which will select first item, something like
```js
$('#id').w2field({
...
onLoad: function (event) {
   event.onComplete = function () {
      // the event object will have what you need, either event.xhr.responseText or event.data
      $('#id').data('selected', {id: xx, text: xxx});
   }
}
});
```

**Comment by samoilis** [comment]
@mpf82 @mrg2001 Thank you for your anwers

but the problem concerns the selection on the list after remote search and not the selection of the value of the field.

When writing on the field and becomes remote search, in the results list is not selected anything 
so that the user forced to used up/down arrows to select a value

in many cases the result is one item, so, in this case is very useful to preselect this item and the user with just pressing Enter assign the value (of the item) to the field.

That I think wanted to make the person who wrote the above code

**Comment by mrg2001** [comment]
@samoilis The solution above works after the search. You can check how many items server returned and select first item or not.
