### ISSUE TITLE
Server/php example

### ISSUE THREAD

**Issue by mendozada** [vitmalina/w2ui#1240]
hi, Vitali , please check the example server / php, users.php not generate the json file correctly. w2ui.js not return cmd == 'get-records'. Thanks, great job.

**Comment by mpf82** [comment]
'get-records' is 1.4.x syntax, while "-records" / "-record" has been stripped from the commands in 1.5

You'll find that most of the examples are still using 1.4 syntax, not just the PHP example.

Feel free to update the example(s) and create a pull request.

**Comment by mendozada** [comment]
Mike, would love me but would need some help, you must use W2lib and W2db or only generated the json in php file. another question is to save the data how. you have any examples?

**Comment by mpf82** [comment]
@mendozada The PHP server includes an example on how to insert/update the records. Just follow the breadcrumbs: users.php `case 'save-record':` -> w2lib.php `saveRecord()` 

Maybe you should try to get the PHP example to work with w2ui 1.4 first. If it runs, you can try to migrate to 1.5 (if you want).

**Comment by spizzi77** [comment]
If you are calling a PHP page, after you must create the right json_encode key=>value and the name of the dimension of the array is "records" an example to create the array is that inside your while->fetch calling the DB you must create an array and you put inside the array all the values and after out of the loop you must do the json_encode for example in this way, for sure you must also create a count foreach records so inside the loop ++$count;

php:
$contaotre= 0;
while($query->fetch()){
++$contatore
			   $arrayRisultati[] = array('recid'=>$contatore, 
			   							 'cdretcod' => cdretcod],
										 'deretcod' =>$deretcod,
										 'nompgm' => $nompgm,
										 'nompgm_ato' => $nompgm_ato,
										 'label'  => $label,
										 'sqlcode'  => $sqlcode,
										 'tabella'  => $tabella,
										 'istruz'  => $istruz,
										 'sqlca'  => $sqlca);
									}	 
				$root['records'] = $arrayRisultati;
				$root = json_encode($root);
				print $root;

And for sure after in client the fields will be the names of the keys of the server array.
Bye

**Comment by mendozada** [comment]
Hi, thank spizzi77 , I am currently using this way to fill the grid. but I do like to know how to use the search. and brings only a record for editing.

`
<?php 
require("conn.php");
$sql = "SELECT * FROM users "; 
mysqli_set_charset($conexion, "utf8"); 
if(!$result = mysqli_query($conexion, $sql)) die();
$clientes = array(); //creamos un array
while($row = mysqli_fetch_array($result)) 
{ 
	$userid=$row['userid'];
	$fname=$row['fname'];
	$lname=$row['lname'];
	$email=$row['email'];
	$login=$row['login'];

	$clientes[] = array('recid'=> $userid, 'userid'=> $userid, 'fname'=> $fname, 'lname'=> $lname, 'email'=> $email, 'login'=> $login);

}
//desconectamos la base de datos
$close = mysqli_close($conexion) 
or die("Ha sucedido un error inexperado en la desconexion de la base de datos");

//Creamos el JSON
//$json_string = json_encode($clientes);
echo '{"status": "success", "records":'. json_encode($clientes).' }';
//echo $json_string;

//Si queremos crear un archivo json, sería de esta forma:
//$file = 'datos.json';
//file_put_contents($file, json_encode($clientes));

?>
`

**Comment by spizzi77** [comment]
Hi Mendozada, sincerely my english isn't very good(i'm italian), but i understand that the problem isn't display records in table but the search function in w2ui?
BTW In PHP i use always a json answer and after in w2ui i manage the array both for success that for error-manage.
I'm a little doubtful about your recid, because i think that the recid must be a count of all records not the userId.
After this you can try in php this:

//Creamos el JSON
$json_string["records"] = json_encode($clientes);
//echo '{"status": "success", "records":'. json_encode($clientes).' }';
echo $json_string;

Instead for the search i notify that in w2ui you must do the call with the load method and not the url inside the options grid, because if i put the link inside the url of the option grid the search highlights the records but not hide the records that aren't in search instead if you create the grid and under you call in this way

w2ui['nameGrid'].load('url.php');

All is working fine..
Hope this help you.
Bye have a good WE

**Comment by chalchis** [comment]
hey this data structure
in json

"status"  : "success",
    "total"   : 36,
    "records" : [
        { "recid": 1, "field-1": "value-1", ... "field-N": "value-N" },
        ...
        { "recid": N, "field-1": "value-1", ... "field-N": "value-N" }
    ]
