### ISSUE TITLE
Will 1.5 be finally released officially?

### ISSUE THREAD

**Issue by gpetrov** [vitmalina/w2ui#1272]
It is being now an year since the last official release 1.4.3 - the version 1.5 is being in the making since then and it seems to be stable enough.

Why isn't it officially released and supported through the w2ui.com site with docs and demos?

This will allows us finally to take it in production.

**Comment by mrg2001** [comment]
Need to finish docs and demos. If you can please help. The source code itself is stable. The docs and demos have been done for some components, but not all yet.

If you open any core file in /src directory, in the top of the file you will see comments of what new in 1.5. This needs to be verified in docs and demos that is is described. Thanks.

**Comment by gpetrov** [comment]
@mrg2001 thanks - will be glad to help - is there a different branch for the docs & w2ui site?

Maybe tag the latest 1.5 as release now?

Can we just separate the old 1.4.2 docs in a separate link - and put the main 1.5 docs as centrals docs.
Also make sure all demos are running the latest 1.5

**Comment by aadrian** [comment]
> Can we just separate the old 1.4.2 docs in a separate link - and put the main 1.5 docs as centrals docs.

+1

It's really important for users in order to be able to quickly migrate  to 1.5 and find bugs to have the docs and live examples for 1.4 but also for 1.5.

**Comment by mrg2001** [comment]
I create a separate branch for each version. So, if you switch to branch called 1.4, all documentation, examples, etc, will be related to 1.4. This means if you do all your changes in current master branch, it will be 1.5.

Once 1.5 is released, master branch for a while will be still 1.5 and be used for minor releases. But as soon as some more or less major changes need to be done, I will cut 1.5.x branch and then current master becomes 1.6. By major I mean when it becomes not completely backward compatible with 1.5. Because all 1.5.x should be completely compatible with each other.

This seems to have worked last time.

**Comment by mrg2001** [comment]
I have posted 1.5.rc1 to the website and removed links to 1.4. Documentation is also available for both of them on the website (for 1.5 whatever current state is, it is somewhat incomplete yet).

**Comment by aadrian** [comment]
> I create a separate branch for each version. 

I mean the live website the users are finding when searching for w2ui.

> I have posted 1.5.rc1 to the website and removed links to 1.4.

This is great!

IMHO the "More demos" demos should be available for both versions: http://w2ui.com/web/demos/#!layout/layout-1  the same way the docs are available too.

When migrating, is very important to have very quickly "before" and "after" examples and fiddles too (not just docs).

Also a short blog message mentioning the update would get the attention of users, since not everybody is monitoring these GitHub issues all the time :) .

Thank you.

**Comment by mcmarinho** [comment]
Thanks, @mrg2001

**Comment by gpetrov** [comment]
Thanks @mrg2001 great work! Maybe add a blog post about this and a separate article about the biggest changes, as well the demos need to be converted to 1.5 as well.

**Comment by TrevorPT** [comment]
> IMHO the "More demos" demos should be available for both versions: http://w2ui.com/web/demos/#!layout/layout-1 the same way the docs are available too.

+1

Congrats on releasing 1.5rc1!  It was great to see the project take off a while back, so thanks to the many contributers and especially to Vitali (@vitmalina) and @mrg2001 for keeping it going.  Unfortunately we're stuck with using 1.4.3 for the foreseeable future as it's working well for us, stability is critical (it's in production), and currently there is no time to spend on upgrading libraries.  So hopefully you will keep both the 1.4 docs and demos/more demos available through w2ui.com as we still reference both frequently.   

Incidentally, it's pretty subtle that you can select the version of Docs to display; I wasn't aware you could until reading this thread.  Maybe add a dropdown indicator?

**Comment by mpf82** [comment]
Now that 1.5 is released, this issue can probably be closed.

**For issues and fixes related to moving from 1.4 to 1.5, please refer to this thread: https://github.com/vitmalina/w2ui/issues/1351**

**Comment by mrg2001** [comment]
Uploaded 1.5 demos, at least those that are available.

**Comment by softage0** [comment]
It's still not released on NPM and not tagged yet.

Any plan to release it?
