### ISSUE TITLE
Text in grid buttons, without translation

### ISSUE THREAD

**Issue by FaustoAstudillo** [vitmalina/w2ui#1293]
Hi,

I have compared last version of your great library with 1.4.3 version and found you have "burned-text-" for grid buttons without chance to translate. 
In previous version you have an  indirect assign of text values, using w2utils.lang. 
Dou you can mantain this easy to globally  translate phrases?

![image](https://cloud.githubusercontent.com/assets/20169069/16711860/5556192c-4636-11e6-9fa6-cf621964a971.png)

Thks in advance

**Comment by mpf82** [comment]
Translation in 1.5 still works the same way as it did in 1.4 (using `w2utils.lang()`).

The difference in the case of the toolbar buttons, that you pointed out, is that in 1.4 the translation happens when the button is declared, in 1.5 the translation happens in `w2toolbar.getItemHTML()`.

You could use w2utils.lang to translate phrases in your project, however I would advise against it, because it would make it hard for you to upgrade (you would have to merge your json files manually).

Instead I suggest you take a look at localization libs like [i18next](http://i18next.com/) - but in the end it's up to you.

**Comment by FaustoAstudillo** [comment]
I can see.
Thanks!
