### ISSUE TITLE
the grid's checkbox can't be unchecked after i checked it.   and some suggestion.

### ISSUE THREAD

**Issue by chenduansheng** [vitmalina/w2ui#1377]
Hi, good moning, here is a bug about the checkbox on the grid,
The checkbox can't be unchecked after i checked on it.
It is goods for 1.4, but in 1.5 it has problem when you set the w2grid's property:   selectType:'cell'

example: 
see http://jsfiddle.net/ya9eerb5/6/
(In this jsfiddle, when you click two or more times on the checkbox , you can see the problem)

thanks

the w2ui is the best UI, and i think that it can be more perfect.
By the way,
 I suggest that,  If a cell is editable in a grid, could we add a tag on it? or some other method to show witch cell is can be edited and witch is can't. otherwise, a user need to click two times on the cell to make sure that if the cell is editable

For w2ui's grid, I also suggest that is there a way to make people can click only one time on the cell to enter editing the cell? not only dbclick, but now user must click two times on the cell to edit it, Should it like excel and only need click one time to edit the cell?

Their is another suggest, if a column is sortable, could we make a tag on it to show that this column is sortable? otherwise, user would not know witch column is sortable and which is not

**Comment by spizzi77** [comment]
Hy, yes i think w2ui is really a perfect librery for my needs, i'm using 1.4.3 in my work(i'm a programmer) because at work the project must be stable and unfortunately 1.5 need again of improvments, there different bug on the grid events and like you said the check and uncheck but also other things, when it will be stable like as 1.4.3 i will update also the project at work, i convinced to use w2ui for grid at work ;)
Instead in my personal page i can use 1.5 1.4.3 is differents, so we need to wait that Vitmalina has time to fix all bugs.
BTW i can give you a suggest to give a feedback to the user for columns that are sortable, you can define on refresh looping the columns where add a class w2ui-sort-up so for example if you want to sort name and last name in your grid and give a feedback to the user you can add the onrefresh event in this way...I do this usually to the sortable column:
Bye....

```javascript
        onRefresh:function (event){
        			event.onComplete=function(){
				$(this.columns).each(function(){	
					//console.log(this);
					$("td:contains('First')").find($('.w2ui-col-header  > div')).eq(0).addClass('w2ui-sort-up');
					$("td:contains('Last')").find($('.w2ui-col-header  > div')).eq(0).addClass('w2ui-sort-up');

				});	              
              };
        },
```

**Comment by chenduansheng** [comment]
@spizzi77 Thank you for your great share and kindness, it really a great method and helpful very much, i had tried your method,  and it works good now. before this, this problem trouble me so much.
And i agree with you, and i also hope Vitmalina has time to fix all bugs

**Comment by mrg2001** [comment]
I fixed the check box issue.

1. As for editable cells, you can use render function for the column and implement it easily
2. One click is selection, therefore editable cells will be 2 clicks. 
3. For sortable columns, you can add a span into caption of the column and make it visual if it is sortable.

**Comment by chenduansheng** [comment]
@mrg2001 
Thank you for your perfect solution and with great patience to expain for me, good luck!
