### ISSUE TITLE
.refresh() closes multisearch popup

### ISSUE THREAD

**Issue by MrDefacto** [vitmalina/w2ui#1474]
Hi,

Calling grid.refresh() closes multisearch box. Maybe it's a feature but It can be quite annoying in case of using automatic refresh (for example periodically updated grids).

I don't see reason why refresh should close multisearch popup.

**Comment by avber** [comment]
+1

The same goes for "Columns On/Off" button

Could you add options to control behavior of these buttons?

**Comment by mrg2001** [comment]
grid.refresh() will refresh entire grid, including toolbar and when toolbar is refreshed, it will close its popups. However, you can just refresh records will update HTML from grid.records array, 

```js
w2ui.grid.refreshBody(); 
w2ui.grid.resizeRecords();
```

Close this issue if it helps, otherwise, please give a use case where it is relevant.

**Comment by avber** [comment]
Use cases

Advanced Search
- Click on Advanced Search
- enter search criteria 
- click Find/Search
- inspect top grid records
- if search result is not desirable, go to step 2, otherwise click somewhere to close search dialog (including a record)

Columns On/Off
- Click on the button
- click on some column name
- inspect grid body 
- if result (list of columns) is not desirable (e.g. you want to hide more columns), go to step 2, otherwise click somewhere to close the dialog

**Comment by MrDefacto** [comment]
Clever. Thx. I'll try. As for now i developed other solution, but Your looks much cleaner ;-)

**Comment by mpf82** [comment]
@avber in my experience, the search popup is too big to keep it open if you want to inspect the result (your use case may differ)

As for the column menu, it's fairly easy to replace it with a dialog of your own design, so a user can show/hide multiple columns at the same time from a popup (in my project, the user can also reorder the columns, set them as frozen (I prefer the term *fixed*), activate printing, activate exporting per column, change ``grid.limit`` and toggle the line numbers). The state of the grid is then saved to the DB.

Example what this could look like:
![w2grid_settings](https://cloud.githubusercontent.com/assets/10152404/22238108/dd1e633a-e20f-11e6-93b9-86064afffd79.png)

**Comment by avber** [comment]
@mpf82 Thank you for suggestion
