### ISSUE TITLE
[FEATURE REQUEST] natural sort

### ISSUE THREAD

**Issue by MrDefacto** [vitmalina/w2ui#1476]
Hi,

Are there any plans for adding natural sort? For example for sorting IP addresses etc

Thx,
D

**Comment by Connum** [comment]
Hi there,

I implemented a new column attribute "sortMode", (pull #1496  currently pending):
If set to "natural", a compare function is used that will result in an order that feels more natural to humans. This can be useful for IP addresses, or when numbers are used in strings, so that "48" (as a string) comes after "9" (as a string) - whereas the default sorting would put it the other way round. You can also pass a compare function in the same way you would use it as argument for Array.prototype.sort().

**Comment by mpf82** [comment]
Closing this issue as resolved, because columns can now have a sortMode ``natural``, see docs: http://w2ui.com/web/docs/1.5/w2grid.columns
