### ISSUE TITLE
onExpand in Tree-like grid

### ISSUE THREAD

**Issue by alexey-vasyunin** [vitmalina/w2ui#1510]
Hello!

I have tree-like grid and try to catch expand/collapse events on tree. But when I add onExpand event listener my grid shows subgrids with every row. "expandColumn    : false" has no effect.  Maby w2grid has other event for expand tree-like grid or has some property to disable expandColumn fully?

**Comment by mrg2001** [comment]
The was a small bug that I fixed in this regard, but let me first explain how it works.

in 1.4 there was expandable records, which means that
- you have expand column with +/-
- when you click expand, it inserts a row after the record with a div that is used to insert some content (you still have to control that divs height)
- if you insert another grid in that div, there was logic for seamless keyboard navigation 
- there were css for this expansion.

in 1.5, in addition to expandable records there is also tree-like grids. If you insert nested records, they become part of the original grid, not a subgrid inside expandable column (which is much less headache).

As of 1.5 on, expandable columns should be used to show some no grid content, but all grid-like content should be implemented with child records. I have removed logic for seemless keyboard navigation (it was quite bad and buggy) and css, though for expandable grid it is still there.

The bug that I mentioned was that if you define onExpand event, it will auto enable show.expandColumn, which is not used in tree-like grid. 

Let me know if this helps you with your bug.

**Comment by mrg2001** [comment]
If not, please create JS fiddle where you illustrated the problem.

**Comment by alexey-vasyunin** [comment]
Ok, thanx for reply.  Yes, I've defined onExpand event to watch tree-like expand nested (children) records, because there are no other events to catch this.  And expand() method expands tree-like "branches".

**Comment by mrg2001** [comment]
expand() will expand either children (if they exist) or div if no children

**Comment by mcmarinho** [comment]
offtopic

@mrg2001, you and vitmalina are same person?

2017-02-11 20:22 GMT-04:00 mrg2001 <notifications@github.com>:
