### ISSUE TITLE
records status is not update to modified. Issue refrance #1552

### ISSUE THREAD

**Issue by jackryu** [vitmalina/w2ui#1555]
thanks - @mpf82  for resolved this issue : Set object is not update all records  #1552 
**But this is not resolved completely**   description below  
------------------------------------------------------------------------------

** records status is not update to modified.** 

_This code is not fill data in changes object so my changes  object is display empty._

> var updatedRows=w2ui['gridIABU'].changes;

_**this red mark**_
![image](https://cloud.githubusercontent.com/assets/6933841/24305208/2e56e5b4-10e2-11e7-8fdf-4ea2c78197e4.png)

but this is showing blank.... 

**all record selected but red mark identifier is not showing on records**

**Comment by spizzi77** [comment]
Hi,
But it's .changes a valid method?
I use getChanges

http://w2ui.com/web/docs/1.5/w2grid.getChanges

**Comment by jackryu** [comment]
@spizzi77   _.getChanges Not Working........ I am already tried both method._  

_@mpf82  Please help - this is urgent for me this issue in production based application._

**Comment by jackryu** [comment]
Issue detail  -  if you are update any record manually then record add "w2ui-changed" this class for showing updated records and showing Red mark . But in my select all code this class not added this is a problem. and I am try to getting change record this is not working - 

My select all code is provided by #1552 @mpf82  

`  set: function (recid, record, noRefresh) { // does not delete existing, but overrides on top of it
        if ((typeof recid == 'object') && (recid !== null)) {
            noRefresh = record;
            record    = recid;
            recid     = null;
        }
        // update all records
        if (recid == null) {
            for (var i = 0; i < this.records.length; i++) {
                $.extend(true, this.records[i], record); // recid is the whole record
            }
            if (noRefresh !== true) this.refresh();
        }
`

**Comment by spizzi77** [comment]
Hy jackryu,
Well, i think here we have two problems, if i understand well you have a columns with checkbox, but this checkbox column isn't the multiselect of the object but it's a column that YOU created with checkbox, is it right?Did you want that when the user check this checkbox you want display the w2ui-cahnged class?
Because this is one problem, the other problem is that the .changes isn't a valid method and you must use the .getChanges.
Well you can see on my site under the menu "esempiW2ui"->Ex.ple W2Grid 1.5.1 ONLY onSelect that 
the edit column(Citta Residenza) it's working well.

https://fractalcosmo.com/MvcWebLog/paginaDefault.php

You can do a multiselect untill 5 records(this is wanted by me) and when you click "variazione residenza" you can see in console browser that the array final is corrected.There is only a bug in w2ui 1.5.1 using both onSelect that onClick, because there are not working together with multiselect, it's an issue that i opened days ago.
But the edit seems work fine.
Your problem it's that you want to display w2ui-changed also only checking the checkbox?
But you must this on the onClick checkbox and force the w2ui-changed css, for sure because you are not editing a checkbox.
If i understand well the problem.
The other problem is that if you use onClick and onSelect events together after you will not able to do a multiselect, this is a bug, hope this will be fixed soon, you can see this in my examples w2Grid 1.5.1 onClick OnSelect not working instead w2Grid 1.4.3 onClick onSelect it's working well.
So where is the problem?Only insert the w2ui-changed when you click your column of checkboxes?You can do this but you must do at every click of the checkbox.
In next days i can try to add a column checkbox in that grid and try to resolve it for you, if this is the problem.
Bye
Andrea

**Comment by jackryu** [comment]
> **I am try to explain again --**  

**Snapshot** 
![w2uigrid](https://cloud.githubusercontent.com/assets/6933841/24462026/92cad0f0-14c0-11e7-81c1-dd9b25042b17.png)

**Issue** 
> if i am select all checkbox (Column : Include [2]) using Button (Select (1)) this button select all check box.  _code in select all button Ref : Code 0.1_
> 
> But my save button (3) not enable if i am try to enable this button by forced then i am not getting any thing in getChainge object code in Save button (0.2). 
> 
> _I am Try Changes and getChanges both function._

**Code 0.1 :** 

> set: function (recid, record, noRefresh) { // does not delete existing, but overrides on top of it if ((typeof recid == 'object') && (recid !== null)) { noRefresh = record; record = recid; recid = null; } // update all records if (recid == null) { for (var i = 0; i < this.records.length; i++) { $.extend(true, this.records[i], record); // recid is the whole record } if (noRefresh !== true) this.refresh(); }

_this code suggest  in - #1552  this issue_ by @mpf82

**Code 0.2 :** 

>       onSave: function (event) { var $BinsChangesJOSN = JSON.stringify(event.getChanges); }

**Comment by spizzi77** [comment]
Here's a little of confusion, you asked the reason because the red triangle of w2ui-changed class is not showing in your include column; 
That triangle is showing when a user do an Edit Field, instead clicking the select button and check all the checkbox is not an edit field event so it's normal that the triangle red wui-changed is not showing, if you want to able the save button when you click the "select" button, this is another problem, and you must able the button on the onClick event of the "Select" button and write 

$('#tb_'+nameGrid+'_toolbar_item_w2ui-save').removeClass('disabled');

But an arrow at your side it's that really this seems a bug because also in the w2ui demo the save button is not able....Like as in this example:

http://w2ui.com/web/demos/#!grid/grid-17

You can force the removeClass disabled but also if you force the removeClass disable seems that there is not attached the event so you can't click the save button; 
Btw i always use custom buttons to save i don't use the onSave event so i didn't see this.
I suggest to put a button in your toolbar and not use the save event untill this bug it isn't fixed.

Ciao
Andrea

**Comment by jackryu** [comment]
> thanks for support but getChanges  object is still empty so how can find selected records ?

**Comment by spizzi77** [comment]
I done a little variation at the grid that you see on my site:

https://fractalcosmo.com/MvcWebLog/esempiW2ui.php?versione151OnlyOnSelect

I attach you the code of the all javascript of all the grid, but using two checkbox column means do more work, do you know, because you must control everything.
Now a quickly logic it's this:

Create a button, in this case i named Get Selection Check, a quickly idea it's do two loops, one to get all the records and one to get the recid of checked, you can see i named the column CHECK, in the function 
getSelectedCheck you get all the records and all the checkbox id checked after inside the records loop you get that recid selected from the loop of the checked and push in array all the value....I done only half work you need to do other half.
The first console.log are the recid checked after you must use these recid checked and if recid of checked is equal to recid of records you get the values and push them in an array.
At the end you will have the array to send to the server....
Ciao
Here you go:
```html
	<div id="risultatiVerione151">
		<div class="spacer10"> </div>
		<div class="containerBorderBlank" id="panelRisultatiVersione151">
			<div id="gridVersione151" style="width:100%;height:100%"> </div>
		</div>
	</div><br>
```

```javascript

$(document).ready(function(){	
	
	timestamp = new Date().getTime();
	//Sempre la destroy altrimenti va in errore di name già definito se viene chiusa e riaperta
	$().w2destroy('gridVersione151');
	//E lo show del div della griglia
	$('#gridVersione151').show();

	//un css di default
    $('#gridVersione151').css({ width: '100%' }).animate({ height: '100%' }, 100);
	$('#gridVersione151').w2grid({
        name: 'gridVersione151',
        header : '<div class=""><b>Esempio Dati w2ui Versione 1.5.rc1</b></div>',
        multiSelect : true,
        fixedBody : false,
        msgNotJSON: '<div style="text-align:center"><b>Non ci sono validi risultati</b></div>',
        show: {
            header       : true,
            toolbar      : true,
            footer       : false,
            lineNumbers  : false,
            selectColumn : true,
            expandColumn : false,
            toolbarColumns : false,
	        toolbarSearch : true,
			toolbarReload : false,
        },
        toolbar : {items:[
	              { type: 'button',  id: 'itemVariazione',  caption: 'Variazione Residenza', icon: 'glyphicon glyphicon-edit', hint: 'Variazione Residenza' },
	              { type: 'button',  id: 'itemGetRecordSelected',  caption: 'Get Selection Check', icon: 'glyphicon glyphicon-edit', hint: 'Get Selection on Check column' },
	        ],
	        onClick: function (event) {
	        	if (event.target == 'itemVariazione'){
	        		variazioneDatoResidenza(arrayValori);
	        	}
	        	if (event.target == 'itemGetRecordSelected'){
	        		getSelectedCheck();
	        	}
	        },	            
	    },  
        columns: [               
            { field: 'nome', caption: '<div style="text-align: center;">Nome<div>', sortable:true,size:'10%',attr: 'align=center' },
            { field: 'cognome', caption: '<div style="text-align: center;">Cognome<div>',sortable:true,size:'10%',attr: 'align=center'},
            { field: 'dataNascita', caption: '<div style="text-align: center;">Data Nascita<div>',size:'8%',sortable:true,attr: 'align=center'},
            { field: 'cittaResidenza', caption: '<div style="text-align: center;">Città Residenza*Double click to edit*<div>', sortable:true,size:'20%',editable: { type: 'text',style: 'background-color: #ffcccc' } },
            { field: 'input', caption: 'Check', sortable:true,size:'20%',editable: { type: 'text',style: 'background-color: #ffcccc' },render:function(record){
            	return "<input type='checkbox' name='checkGrid' class='checkGrid' style='text-align:center' value='"+record.recid+"'>";
            } },
        ],
        searches: [
            { type: 'text', field: 'nome', caption: 'Nome',operator:'contains' },
            { type: 'text', field: 'cognome', caption: 'Cognome',operator:'contains' },
            { type: 'text', field: 'dataNascita', caption: 'Data Nascita',operator:'contains' },
            { type: 'text', field: 'cittaResidenza', caption: 'Città Residenza',operator:'contains' },
	    ],
        onChange: function(event){
        	event.onComplete = function(event) {
        		$(window).click(function(event){
					$('.w2ui-changed').each(function(event){
					  	$('.w2ui-changed').css('color','red');
					});
        		});	
        	};
        },
        onRefresh:function(event){
        	event.onComplete=function(event){
        		$('#grid_gridVersione151_check_all').hide();
        		//Inseriamo un title sulla input ricerca
        		$('#grid_gridElencoToDo_search_all').attr('title','Tutte le colonne sono ordinabili e ridimensionabili');
        		records = this.records;
        		colonne = this.columns;
    			totaleRisultati = this.totaleRisultati;
				console.log(totaleRisultati);
        		//Inseriamo l'icona di sort al refresh ready della tabella per dare un feedback all'operatore
        		$(colonne).each(function(event){
        			$("td:contains('Nome')").find($('.w2ui-col-header > div')).eq(0).addClass('w2ui-sort-up');
        			$("td:contains('Cognome')").find($('.w2ui-col-header > div')).eq(0).addClass('w2ui-sort-up');
        			$("td:contains('Data')").find($('.w2ui-col-header > div')).eq(0).addClass('w2ui-sort-up');
        			$("td:contains('Residenza')").find($('.w2ui-col-header > div')).eq(0).addClass('w2ui-sort-up');
        		});        		
        		
        	};
        },
        onLoad:function(event){

			var response = [];
			var responseText = (event.xhr.responseText);
			//console.log(responseText);
			response = responseText.match(/{.*(.*)\}/);
			
			if (response != null){
				var finale = response[0];
				var arrayFinale = JSON.parse(finale);
				var nazione = arrayFinale.nazione;
				var nazionalita = arrayFinale.nazionalita;
    			var totaleRisultati = arrayFinale.totaleRisultati;
				console.log(totaleRisultati);
				console.log(nazione);
				console.log(nazionalita);
				var records = arrayFinale.records;
				$(records).each(function(event){

				});
			}    	
        },
        onEditField:function(event){
        	//console.log(event);
        	//console.log(this);
        	event.onComplete=function(event){
        		//console.log(this);
        		//console.log(event);
        		id = event.recid;
				$('#grid_gridVersione151_edit_'+id+'_3').keypress(function(event){
					 return noNumeri(event);
				});
				$('#grid_gridVersione151_edit_'+id+'_3').blur(function(event){
						stringa = this.value;
						repStringa = (stringa.replace(/[^a-zA-Z ]/g, ""));
						$('#grid_gridVersione151_edit_'+id+'_3').val(repStringa);				
				});
        	};
    		$('.w2ui-changed').each(function(event){
			  	$(this).css('color','red');
			});
        },
        onSelect : function (event){	
        	target = event.target;
			//Oltre i 5 record selezionati blocchiamo con un unselect la possibilità di selezionare altri record
			$.fn.bloccaSelezione = function(event){
				var record = event.recid;	        		
        		w2ui['gridVersione151'].unselect(record);
			};
			
        	event.onComplete = function(event) {
        	   //La getSelection ritorna le checkbox selezionate
		       sel = this.getSelection();
		       //console.log(sel);
		       arrayValori = [];

		       if (sel.length == 0){
					w2ui['gridVersione151'].toolbar.disable('itemVariazione');
		       }
			   else{
					w2ui['gridVersione151'].toolbar.enable('itemVariazione');			   	
			   }
			   
		       if (sel.length > 5){
				  $(this).bloccaSelezione(event);
				  return;
		       }			   
			   
		       //Al select delle checkbox inseriamo in un array chiave valore tutti i record 
		       for (i=0; i < sel.length;i++){
		       	  //console.log(w2ui[target]);
		          recidRecord = sel[i];	
		          //Il recid parte da 1 ma il target parte da 0 quindi mettiamo -1				        	
			      record = w2ui[target].records[recidRecord-1];
			      console.log(record);
				  recid = $.trim(record.recid);
				  id = $.trim(record.id);	
				  nome= $.trim(record.nome);
				  cognome = $.trim(record.cognome);
				  dataNascita = $.trim(record.dataNascita);
				  cittaResidenza = $.trim(record.cittaResidenza);
				  arrayValori.push({recid:recid,id:id,nome:nome,cognome:cognome,dataNascita:dataNascita,cittaResidenza:cittaResidenza});
		       }

		    }; 
		    			
    	},
        onUnselect : function(event){
			target=event.target;
			event.onComplete = function(event) {
			    sel = this.getSelection();
			   	arrayValori = [];
		        if (sel.length == 0){
					w2ui['gridVersione151'].toolbar.disable('itemVariazione');
		        }
			    else{
					w2ui['gridVersione151'].toolbar.enable('itemVariazione');	   	
			    }
		        //Sull'unselect va aggiornato l'array delle checkbox 
		        for (i=0; i < sel.length;i++){
		       	  //console.log(w2ui[target]);
		          recidRecord = sel[i];	
		          //Il recid parte da 1 ma il target parte da 0 quindi mettiamo -1				        	
			      record = w2ui[target].records[recidRecord-1];
				  recid = $.trim(record.recid);
				  id = $.trim(record.id);
				  nome= $.trim(record.nome);
				  cognome = $.trim(record.cognome);
				  dataNascita = $.trim(record.dataNascita);
				  cittaResidenza = $.trim(record.cittaResidenza);
				  arrayValori.push({recid:recid,id:id,nome:nome,cognome:cognome,dataNascita:dataNascita,cittaResidenza:cittaResidenza});
		        }
			};     	
    	},
    	onClick:function(event){
    		//event.preventDefault();	
        	/*event.onComplete = function(event) {
	    		id = event.recid;
	    		//console.log(id);
	       		$('#grid_gridVersione151_rec_'+id).find('td').eq(4).click();				
        	};*/    		
    	},
		onError:function(event){
			event.preventDefault();
			numeroErrore = event.message.errore;
			if (numeroErrore == '99'){
			  	div = $('<div class="info">').html('Nessun dato Presente<br><br>');
				$('#panelRisultatiRecapitianagrafe').append(div);
			}
		},
	});
	
	params = $.param({
		timestamp : timestamp,
	});
	
	w2ui['gridVersione151'].load('esempiW2ui.php?versione=griglia151&'+params);
	w2ui['gridVersione151'].resize();
	w2ui['gridVersione151'].toolbar.disable('itemVariazione');
	
});

function getSelectedCheck(){
	
	records = w2ui['gridVersione151'].records;
	//console.log(records);

	check = $('.checkGrid:checkbox:checked');
	
	$(check).each(function(){
	  
	  value = this.attributes.value;
	  console.log(value);
	});

	$(records).each(function(){
		console.log(this);
	});
	
	
}

function variazioneDatoResidenza(arrayValori){

	residenzaCambiata = w2ui['gridVersione151'].getChanges();
		
	//Abbiamo recuperato i campi ma dobbiamo controllare se sono state editate le residenze, se il recid è stato
	//editato prendiamo le nuove residenze editate, lo facciamo qui quando l'operatore clicca la variazione che poi manda al server
	$(arrayValori).each(function(i,j){
		idArray = arrayValori[i].recid;
		console.log(idArray);
		$(residenzaCambiata).each(function(k,w){
			recidEditato = residenzaCambiata[k].recid;
			//console.log(recidEditato);
			residenzaEditataAggiornata = residenzaCambiata[k].cittaResidenza;
			if (recidEditato == idArray){
				arrayValori[i].cittaResidenza = residenzaEditataAggiornata;
			}	
		});
	});
		
	console.log(arrayValori);	
		
}

```
The Json result when the grid call/load the php can be seen here

https://fractalcosmo.com/MvcWebLog/esempiW2ui.php?versione=griglia151

Ciao
Andrea

**Comment by jackryu** [comment]
_Thanks for support @spizzi77  - This is complex code but ok I will try to make code as per your suggestion_  if you have any simple solution please suggest.

**Comment by spizzi77** [comment]
Hy Jackryu,
It depends of what you must do with the second checkbox column(the inlude column), my example has two buttons, one work for the onSelect or OnUnSelect event of the w2ui grid object the other button is working only for the second column checkbox like as your inlude column....But you have just all two examples to see, copy my code but just comment this, because i haven't attached noNumeri function, but you can comment it. 

				$('#grid_gridVersione151_edit_'+id+'_3').keypress(function(event){
					 return noNumeri(event);
				});
If you must only check if the checkbox in the column is checked when the user do the onSelect event, you can do it with a simple _id_numberColumn is(':checked'), it depends from what you must do with that include column checkbox...
Bye
Andrea

**Comment by jackryu** [comment]
**Thanks @spizzi77  i will try...**

**Comment by jackryu** [comment]
My issue is not resolve.

**Comment by mrg2001** [comment]
in records array, all fields are kept in the direct object
```js
grid.records = [{ field1: 1, field2: 2}, {...}...]
```
However, after you changed a field, 2 copies will be stored: old one and new one. The new one in rec.w2ui.changes. So, I am guessing if you modify that, and refresh grid, then it will show the triangle.

Just a guess. See if this helps.

**Comment by jackryu** [comment]
Hello - I tried your suggestion @mrg2001 

```
                    w2ui['vwgrid'].changes = [{ 'recid': 81, 'Include': false }]
                    w2ui['vwgrid'].refresh();
                    var grid = w2ui['vwgrid'].changes;
```
In "grid" variable one record is shown but on UI my check box is still checked and red mark is not shown in front of updated record.

Current Problem : Only UI is not updated and  red mark not shown.

Your suggestion is good and you are very close to fix my problem thanks for your good!! suggestion.

_Please help and suggest how to show red mark and update UI checkbox_

**Comment by mpf82** [comment]
@jackryu in the code you posted you're never touching ``record.w2ui.changes`` as @mrg2001 suggested.

Tip: Change one record manually, so that the red marker shows up and inspect that single record (log in to the console) and wou will see that your record now has a property ``w2ui``.

**Comment by jackryu** [comment]
No this is not working .......

```
w2ui['vwgrid'].records[0].changes= [{ "recid": 97, "Between_Call_Marker": 0 }]
w2ui['vwgrid'].refresh();
```

**Comment by mrg2001** [comment]
Please create a jsFiddle and I will fix it there.

**Comment by jackryu** [comment]
https://jsfiddle.net/JackRry/z5nvLf6j/2/#fork

this is a jsfiddle link but W2ui not working on jsfiddle but my code is attached.

**Comment by jackryu** [comment]
Please Help......... ?

**Comment by mrg2001** [comment]
Here you go http://jsfiddle.net/z5nvLf6j/10/

**Comment by jackryu** [comment]
Thank!! You @mrg2001 appreciated!!!! your help.
