### ISSUE TITLE
column size distribution

### ISSUE THREAD

**Issue by dattto** [vitmalina/w2ui#1594]
I try to have grid with 48 columns (numbers 0-47). If I set each column width to 2% (100%/48) I get:
![2perc](https://cloud.githubusercontent.com/assets/13716631/25839368/fdaacb88-349f-11e7-986a-ce239052b563.PNG)
If I set each column width to 22px, I can see that this layout can easily fit:
![22px](https://cloud.githubusercontent.com/assets/13716631/25839387/15b16dd6-34a0-11e7-8d39-24f90a4143a2.PNG)
 
Why the % size option isn't able to distribute them evenly without hiding?

**Comment by mrg2001** [comment]
48*2 is 96. The grid will normalize your % distribution. For example if you defined 4 columns of 50% each, then effectively, each column will be 33.3% of what ever width it had. This is what happening in your case as well, since it is less then 100%, it will redistribute width. You can see calcualtedWidth of columns if you read grid.columns array
```js
console.log(grid.columns)
```

Why it is hiding (putting ... in the column name) I do not know. It is purely done by css. If you can create a jsFiddle, I can look into it.

**Comment by mpf82** [comment]
@mrg2001 This issue can probably be closed due to inactivity.

**Comment by mpf82** [comment]
Closing issue: no response
