### ISSUE TITLE
Date type field in Grid advanced-search box with latest(nightly) build

### ISSUE THREAD

**Issue by thomasguo** [vitmalina/w2ui#1616]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

If MultiSearch is enabled in Grid and there is a date-type field in searches,  the box will dismiss after we pick the date.

* **What is the expected behavior?**

While picking a date, we dont want the advanced search box disappear. We want that only after clicking the Search button in the popup search box.

* **Other information**

This issue only exists in the nightly build version(w2ui.js). It does not  exist in the 1.5-RC1 version.

**Comment by mpf82** [comment]
This might be related to the behaviour of the color picker in the search dialog, see https://github.com/vitmalina/w2ui/issues/1323

**Comment by Spievat** [comment]
I'm experiencing this same issue with the date type field, but I've identified that for me the bug is created when I combine Advanced Search, Dates and the **Tree-Like Grid**.

Fiddle with advanced search and dates - which works fine:
http://jsfiddle.net/api/post/jquery/2.1/

Fiddle with advanced search, dates, and **Tree-Like Grid** - which breaks:
http://jsfiddle.net/mwbypLah/

I have confirmed that this is using the nightly build (http://rawgit.com/vitmalina/w2ui/master/dist/w2ui.min.js), and that the issue is resolved using the 1.5-RC1 build, downloadable from http://w2ui.com/.
