### ISSUE TITLE
Need one example of the following...

### ISSUE THREAD

**Issue by prog20901** [vitmalina/w2ui#1659]
Could you please kindly consider adding one more example html file with the following features...Please kindly attach to the project examples folder as it would be helpful for many as well..

1. Read only grid as above without edit, delete and save option.
2. The grid with many export options - pdf, csv, excel, word etc.,
3. When the pagination is enabled - goto page option to navigate to particular page
4. Copy to clipboard and print option
5. Support quickest rendering for alteast 5,000 rows with page size as 10, 100, 500, 1000, 5000
6. Search all columns or individual columns
7. Export selected or all columns

Example grid
http://institut-de-genomique.github.io/Ultimate-DataTable/
https://w3lessons.info/2015/07/13/export-html-table-to-excel-csv-json-pdf-png-using-jquery/

Reference
http://2.bp.blogspot.com/-yTiytux2848/Vcj-b5FjyUI/AAAAAAAAdQk/8rzPAsyU4Dw/s1600/jQuery%2Bdatatables%2Bexport%2Bto%2Bpdf.png
2 . https://www.phpflow.com/wp-content/uploads/2015/09/export-table-data-toexcel-png-pdf.png
https://i.stack.imgur.com/XeCzz.png

**Comment by mpf82** [comment]
1) The grid is read-only by default. You may decide to disable / hide the buttons you do not want or hide the grid's toolbar completely. [reference](http://w2ui.com/web/demos/#!grid/grid-1)
2) For Excel/CSV export, this (declined) pull request might be helpful: [reference](https://github.com/vitmalina/w2ui/pull/777/files). Personally, we are doing all exporting in the backend (Python server), because it's more flexibale and you can support much more formats, compared to JS exports, e.g. writing *real* Excel files that can also have embedded images, not just CSV.
3) w2grid has no pagination, instead it has endless scrolling. There's an example with up to 1 million records. [reference](http://w2ui.com/web/blog/7/JavaScript-Grid-with-One-Million-Records)
4) You can already copy a selected row to clipbaord with CTRL+C
5) What's "quickest rendering"? I suggest you filter your data instead. Which user would want to scroll through 5000 records?
6) You can already decide to search all or individual fields in the quick search. [reference](http://w2ui.com/web/demos/#!grid/grid-3)
7) If you can export your data (see (2)) it should be easy to decide if you export all records or only the selected ones.

Cheers =)

**Comment by jkathir** [comment]
Thanks for your patience and kind reply to all the questions. It was really helpful. I loved the http://w2ui.com/web/demos/#!grid/grid-3 example. Could you please kindly add a new example with exact same above grid and add 2 export options and goto page to the grid? This is the best grid which suits me ....Is it responsive and static data can be rendered?

**Comment by mpf82** [comment]
Closing issue: exporting is out of the scope of the w2ui library and there's no "goto page", there's endless scrolling. All other questions have already been answered.
