### ISSUE TITLE
Grid summary has duplicate summary rows when data change

### ISSUE THREAD

**Issue by eliavmaman** [vitmalina/w2ui#1669]
@jianwu 
* **I'm submitting a ...**
[ ] bug report

* **What is the current behavior?**
Grid summary has duplicate summary rows when data change, i also created that [Gist](https://gist.github.com/eliavmaman/7d10217fdbb61c807f7e3fd6d03e3a12)
to show the current behavior .

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots**.

![image](https://user-images.githubusercontent.com/6911449/30118824-ad50978a-932c-11e7-8414-08d28ee608a7.png)

* **What is the expected behavior?**
grid will have summary rows as defined

Can u please assist?

**Comment by eliavmaman** [comment]
@jianwu  any idea please?

**Comment by mpf82** [comment]
If a "normal" record is identified as a summary record, it is moved (copied) to ``grid.summary``.
If you keep adding summary records the way you're doing, ``grid.summary`` will grow.

You can either clear only the summary records before setting ``grid.records`` with ``w2ui['grid'].summary = [];``
\- or -
you could call ``w2ui['grid'].clear();`` - which is the preferred way, because it takes care of resetting everything, even stuff that might change in the future.

**Comment by mpf82** [comment]
@eliavmaman Is your problem now resolved? Can this issue be closed?

@mrg2001 / @vitmalina : please consider to close this due to inactivity and because @eliavmaman already received a detailed explanation why this happens, including a work-around.

**Comment by mpf82** [comment]
Closing issue as resolved
