### ISSUE TITLE
w2ui.grid get data with parameter

### ISSUE THREAD

**Issue by AykutDev** [vitmalina/w2ui#1758]
I want to implement w2ui grid and get data from server with parameter.I try to this way but ID posted null so what i am missing here?

 ```
 function databindSquadMembers(ID) {       
           $('#myGrid2').w2grid({
               name: 'myGrid2',
               url: 'member/Find',
               method: 'GET', 
               show: {
                   toolbar: true,
               },
               columns: [
                   { field: 'PersonalCode', caption: 'PCode'},
                   { field: 'FullName', caption: 'fName'},
               ],             
               postData: {
                   ID: ID,
               },
           });
       }
```
Even if i try to this again ID is showing on controller null
```
postData:{
           ID: 'ID', //or ID:'123'
              },
```
And here is the server side;

```
public JsonResult Find(string ID)  {
     Squad squad = SquadFinder.FindByID(ID);
     IEnumerable members = squad.Members.Cast<SquadMember>()
                    .Select(p => new
                    {
                        id = ID,
                        PersonalCode = p.Employee.Code,
                        FullName = p.FullName,
                        Email = (null != p.Employee ? p.Employee.Email : "")
                    });
    return Json(members, JsonRequestBehavior.AllowGet);
 }
```
**Edit!!**
I add to utils and now it is working.
`w2utils.settings.dataType = 'JSON',
`

**Comment by mpf82** [comment]
To make it easier to help, you should add a bit of information.

- What version of w2ui are you using?
- What's your dataType (grid.dataType / w2utils.settings.dataType)? (since you're overriding grid.method with GET, this should probably be RESTFULL or RESTFULLJSON).
- What's the content of event.postData of your grid's onRequest event?
- What's the actual payload sent to the server (in Chrome you can find this in your dev console -> Network -> Headers ->Request Payload)?
- What technology are you using for the backend (PHP / Python / C# / ...)?
- How are you handling the data in the backend (server)?

You should also add this information to your question on SO: https://stackoverflow.com/questions/49488254/w2ui-grid-get-data-with-parameter

**Comment by mpf82** [comment]
Closing issue: no response, self-answered on SO
