### ISSUE TITLE
Cell colors

### ISSUE THREAD

**Issue by haz9e** [vitmalina/w2ui#1794]
Hi, i made a Grid and fill it with the desired values then i use a function to color the background of the cells one by one, depends on the value of the cell, the color changes...

```
for(var` x=0; x < w2ui['grid'].records.length; x++){
    for(var y=8; y < w2ui['grid'].columns.length; y++){
        var countDays = $( "#grid_grid_data_"+x+"_"+y ).find( "div" ).text();
        var value= countDays;
        var color=_this.getColor(countDays);

//This is the line i use to change the cells color
 ->    $( "#grid_grid_data_"+x+"_"+y ).css( 'box-shadow', 'inset 0 -6px 0 0 ' + color );

    }
}
```

Unfortunately, the colors disappear when i scroll down the list or when I hide then show the grid...

I've read all the similar issues but none of them really match with mine.

I've tried different ways like:

```
w2ui.grid.get(3).style = { 
    11: 'color: white; background-color: #8BC386', 
    12: 'color: black; background-color: #BFE6FF' 
};
```

But this doesn't work

Thanks for your time.

**Comment by mpf82** [comment]
w2grid uses "virtual scrolling" and only the cells that are visible are rendered in the website's DOM.

If you scroll, cells that are no longer visible are removed and the new cells will be constructed to be displayed in the DOM.

That's why your first approach does not work.

your second approach should work for w2ui 1.4

Since w2ui 1.5 all w2ui specific properties must be wrapped in a ``w2ui`` object.

So ``grid.record.style`` becomes ``grid.record.w2ui.style``.

The following works and I will add it to the styling demo at http://w2ui.com/web/demos/#/grid/29

        w2ui.grid.get(8).w2ui = {
            style: {
                0: 'text-decoration: underline overline;',
                1: 'background-color: silver !important; font-weight: bold;',
            }
        }
