### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by mirannda** [vitmalina/w2ui#1796]
Is this project still active, forecasts for new versions?

Thanks

**Comment by bwl21** [comment]
I really do hope that this awesome project is still active - even if there are loads of open issues :-)

**Comment by STiAT** [comment]
Since the last commit was back in April, I'd say it's not active anymore, at least not at the moment.

**Comment by lhaig** [comment]
Commits have been made since then perhaps @mirannda you could close this issue :-)

**Comment by bwl21** [comment]
To be honest, I would appreciate a message from @vitmalina about his plans with this project before closing it.

**Comment by vitmalina** [comment]
@bwl21 thank you for your contribution to the project and the questions. Yes, I know it has been quite slow in w2ui development and I would like to explain what is going on and what is the future of the project. First of all, I continue to love w2ui and use it in ALL the projects I am working on. I know it is kind of cheasee to come from the creator, but it is true. I rarely do anything that doesn't use w2ui. I play with pretty much everything in JS world. All new frameworks (react, vue, etc) and all new ES6/7 features. However, I still think that w2ui has a unique place that other frameworks/libs do not fill and therefore I see its importance and a future for it. 

I am also grateful to all contributors to the project. Small or big, but 119 people directly contributed and many more contributed their time and efforts in bug hunting and fixing. Much appreciated. I do try to review pull requests and merge or comment on them. I am also workign with a few companies that use w2ui and consult them on the matter. Some bug fixes and new features come from them. Most effort is spent in small things and I do envision any big features coming to w2ui, just because I feel it is quite complete and I do not miss anything in my development that I would want to add to w2ui (at least now). Granted, browsers change, JS is evolving and it might require some rework of the code (arrow functions, removing depenency on jQuery, etc) in the future. 

As for bugs submitted on github - most of them are not bugs. They are questions, feature requests, some misunderstanding how to use the lib, etc. Unfortunely, I do not have enought time to help everyone, as it is all I would be doing. At some point I was responding to each request/question and was spending 2-3 hours a day helping people. I did it for about a year, but I just cannot help everyone. There are some bugs on github, but they are not critical. My assumption is if it is someone pain point, they should fix it and share with the rest of the world. I will be happy to review and merge them. Also, just for you, if you have a bug or two that drive your crazy, send me issue #'s and I will review/fix it for you :) - limited time offer :)

Finally, I think I need to update documentation a bit. This is why it is in RC1 and not final release. When I find time, I will do it. This is the only thing that I feel hangs "over my head" currently about the project. Thank you.

**Comment by bwl21** [comment]
@vitmalina Thank you very much for the detailed reply. I hope my request for a statement did not appear as a complaint - otherwise i apologize for this.

I fully agree that w2ui is basically feature complete. It is also unique compared to React and all the other frameworks. It is the small footprint and the fact that it does not introduce a particular processing model which makes it highly attractive. I did not find real alternatives. This was exactly what I was worrying about. What shall I do if w2ui I no longer alive. You destroyed these worries.

I do not have mission critical issues, even if there are some topics:

1. Would like to use font awesome 5 which has more icons #1797 
2. Would like to see a flat design - I sometimes think of writing another theme, but then the sheer amount of parameters make me hesitating.
3. Tooltips on tabs #1322 

thank you once more for your statement and w2ui.

**Comment by STiAT** [comment]
Feature complete - yes. But the software is still in a RC cycle, and there
are issues here and there. If there could be identified critical issues and
pushed to an actual release, that would be a great thing.

I don't think w2ui should stop on a rc1.

I've been using w2ui to "fast" replace desktop-like experience where users
are used to it, to replace hard desktop applications with a web UI. I have
not found any other framework (be it vue, react etc.) where I actually do
that in the manner I can with w2ui. The RC1 is great, but there are issues
as with new jquery libs etc., which are probably fixed in the development
trees. At some point it needs another release or at least a plan to
release, in my opinion.

This is just my personal opinion, and no slight against anyone who made
w2ui possible, and put time and effort into providing us with this great
framework. The contrary, I salute and thank you all. It's just my personal
hope, that this project will survive. There are not many desktop like
experience frameworks for web browsers out in the wild.
