### ISSUE TITLE
function isDate unreachable code after return statement

### ISSUE THREAD

**Issue by spizzi77** [vitmalina/w2ui#1806]
Hello All,
I downloaded the last w2ui.js in line from 190 to 197 is written

```javascript
            val = new Date(val);
            if (retDate !== true) return true;
            return val;
            val = new Date(val);
            year  = val.getFullYear();
            month = val.getMonth() + 1;
            day   = val.getDate();
``` 

Maybe can be written in this way to don't go warning in console?

```javascript
            val = new Date(val);
            if (retDate !== true) return true;
            return val;
            //val = new Date(val);
            //year  = val.getFullYear();
            //month = val.getMonth() + 1;
            //day   = val.getDate();
``` 
Ciao
Andrea

**Comment by mendozada** [comment]
Hello Andrea, I have commented the lines from 191, so that the dd / mm / yyyy format works correctly and it works very well for me.

//		} else if (String(new Date(val)) != 'Invalid Date') {
//            val = new Date(val);
//            if (retDate !== true) return true;
//            return val;
//            val = new Date(val);
//            year  = val.getFullYear();
//            month = val.getMonth() + 1;
//            day   = val.getDate();

Greetings.
Diego

**Comment by mpf82** [comment]
Closing issue: ``isDate`` has been rewritten, this issue no longer applies to the current code base
