### ISSUE TITLE
Getting Grid Column With Rendered Content To Size Appropriately

### ISSUE THREAD

**Issue by MD00414** [vitmalina/w2ui#1827]
Looking for ideas to address the issue demonstrated in this fiddle: 

http://jsfiddle.net/UberMario/tg6rdsuh/5/

The grid's (table) appears to have sufficient width to fit all the content (Columns 1 and 2), but the dynamically rendered 'Select' column is being clipped on the right.

![tempsnip](https://user-images.githubusercontent.com/38018368/58110005-aa230280-7bbc-11e9-9de0-1fe959ec9b87.png)

**Comment by mpf82** [comment]
You can fix this with CSS:

```
select {
  width: 100% !important;
}
```

Fiddle: http://jsfiddle.net/37yrukn6/

By default, the ``select`` in the grid will have a fixed width of ``75px``.

By setting it to ``100%`` you're making sure it will adapt to the width of the cell.

BTW: You should give the select a distinct CSS class and change my CSS sample accordingly, otherwise it will make all your select elements have 100% parent width, which is probably not what you want.

**Comment by MD00414** [comment]
That works GREAT and is very simple/elegant!  Hopefully I can return the favor soon!
