### ISSUE TITLE
Example how to use export function

### ISSUE THREAD

**Issue by Perezari** [vitmalina/w2ui#1838]
Hello, can someone help me how to add button that call to the export function to csv file.
I saw the function but I don’t know how to use it in the table when I add a button.
Please help.

**Comment by mpf82** [comment]
There's no built-in export of any kind, you will have to implement it yourself.

You may use this declined PR as a starting point: https://github.com/vitmalina/w2ui/pull/777/files

**Comment by Perezari** [comment]
Yes I saw that function already.
Can you give me example of code how to use it with button?

**Comment by ErikDorstel** [comment]
I was looking for a CSV export function for the grid object. Since I couldn't find one, I created one.

`w2grid.prototype.toCSV=function() {
  let records=[{}].concat(this.records);
  Object.keys(records[1]).forEach(key => { if (this.getColumn(key)) { records[0][key]=this.getColumn(key).text; } } );
  return records.map(row => {
    Object.keys(row).forEach(key => {
      if (!this.getColumn(key)) { delete row[key]; }
      else if (this.getColumn(key).render) { if (this.getColumn(key).render.startsWith("float")) { row[key]=row[key].replace(".",","); } } } );
    return Object.values(row).map(value => { return typeof value === 'string' ? JSON.stringify(value) : value } ).toString() } ).join('\r\n'); }`

**Comment by vitmalina** [comment]
Closing the issue as there are suggestions how to do it.
