### ISSUE TITLE
MultiSearch fields cannot be edited when grid is displayed in jquery dialog

### ISSUE THREAD

**Issue by mkaramizrakli** [vitmalina/w2ui#1927]
Hello,

I have two grids in a page. "myGrid" is the main grid, and multisearch can be used without any problems.

![image](https://user-images.githubusercontent.com/68780779/99871708-c064b100-2bed-11eb-8e0d-9331f438352d.png)

When a "myGrid" row is doubleclicked, "grid2" is displayed within a jquery ui modal dialog. When this happens, even though configuration is the same, the multisearch fields in grid2 cannot be edited.

![image](https://user-images.githubusercontent.com/68780779/99871723-dd00e900-2bed-11eb-962a-79e55d6083ab.png)

The complete page code is attached as TXT file.

[issue.txt](https://github.com/vitmalina/w2ui/files/5577251/issue.txt)

Thank you very much for your help.

Cheers

**Comment by mkaramizrakli** [comment]
Any suggestions from anyone will be more than appreciated.

**Comment by vitmalina** [comment]
If you can create jsFiddle and replicate the issue, I can take a look. I think it is likely a z-index issue and could be easily solved with css

**Comment by mkaramizrakli** [comment]
Thx for your reply.

Here is the jsFiddle:

https://jsfiddle.net/mkaramizrakli/qd92kL0r/24/

Cheers

**Comment by vitmalina** [comment]
jQuery UI when you open a dialog has JS code to control elements in focus. I think they do it so that no input gets focus outside of the opened dialog. If you run 
```js
$(document).off('focusin')
```
Then it works. Here is jsFiddle where it works https://jsfiddle.net/jgxu5v8d/1/

BUT Do not user jQuery UI, it is 10+ year old library with little updates. It has nothing that w2ui does not have already. Here is how to do the same with `w2popup` 

https://jsfiddle.net/jgxu5v8d/8/
