### ISSUE TITLE
Dragging of columns doesn't work

### ISSUE THREAD

**Issue by gespo14** [vitmalina/w2ui#2097]
Hi,
I saw that you solved the issue of columns dragging, I have downloaded the new files but columns dragging still doesn't work.
Can you please tell me how to use it or give me an example (fiddle)?

Thanks

**Comment by mpf82** [comment]
Hi. The issue has been fixed in the sources (in the /src directory). The files in ``/dist`` have not yet been recreated. 

Your options:

1. wait for the files to be recreated, you could track the /dist history : https://github.com/vitmalina/w2ui/commits/master/dist
2. create the files yourself, e.g. using gulp and the ``gulpfile.js`` in root
3. use the w2ui sources directly, either as modules or by including ``/src/w2compat.js`` in your project
4. merge the [PR](https://github.com/vitmalina/w2ui/pull/2089/files) into your local w2ui file

Cheers =)

**Comment by mpf82** [comment]
@gespo14 the files in dist have been recompiled

**Comment by gespo14** [comment]
thank you, cheers
