### ISSUE TITLE
Search in grid V2 is not working as expected (like in V1.5)

### ISSUE THREAD

**Issue by boumboum** [vitmalina/w2ui#2124]
- If I'm not specifying explicitly the ` searches: [...]` in the grid definition the search dropdown is not showing anything. Same with the new div appearing below the search input showing empty data (which is IMHO completely useless, so we should be able to disable it at the design level, as it doesn't give us any value add compared to the search popup)
-` textSearch: 'contains'` in the grid definition is not taken into account within the search, even after I have defined the `searches: [...]` entity
- The search is not restricting the shown records according to the entered filter Not even in your demo page. Only highlighting the filter text: [http://w2ui.com/web/demos/#/grid/3](http://w2ui.com/web/demos/#/grid/3). Try to search for `tt`!
-

**Comment by vitmalina** [comment]
I recently refactored search and it seems to work now. 

1. If you do not define `searches` there will be no searches to search by. It is intended behavior. You can hide search bar by setting `grid.show.toolbarSearch = false`
2.  `textSearch` - deprecated in favor of `defaultOperator`
3. In the demo you mentioned, it is not restricted because the demo assumer server side search. I have fixed the demo to do client side search, so it should be working now.
