### ISSUE TITLE
[BUG] Problems with live update

### ISSUE THREAD

**Issue by mansurdegirmenci** [vitmalina/w2ui#2181]
Problems occur on "grid" when "remove" or "add" method is triggered on "grid" with "web socket" from server. When "grid.remove" is used, it gives the error "Your remote data source record count has changed, reloading from the first record". As a complement to the "live updates" feature, this should be fixed. Especially with the data uploaded by the server, there is a problem. 
https://jsfiddle.net/mansurdegrmenci/ekmzday9/29/

**Comment by vitmalina** [comment]
Not sure it is a bug. Let me explain

Your current example has remote data source (grid.url is defined), so, I am explaining in the light of remote data source.

1. If you call `grid.remove(recid)` it will
- remove record from `grid.records` array
- trigger `grid.refresh`, which for remote data source triggers `grid.reload`
- reloads data from remote source

Note, that you server side did not remove the record on the server.

And here is what happens: it realizes that local record count locally and what was returned from remote is different, now, due to infinite scroll, it does not not which page it should re-query (it pulls 100 records at a time), so, it need to dump all pull records and start from the beginning. And it is what is it doing. 

Here is how you work around this issue

When Remove button is clicked do this
```js
fetch('/remove/record/:id')
   .then(() => { grid.remove(:id) })
```

Then it will be all good.

**Comment by mansurdegirmenci** [comment]
I did that because I couldn't make the "remove" button web socket :) imagine a scenario like this. Imagine 20 people working on a list at the same time. Someone is updating, someone is deleting, and someone is adding. The data should be reflected instantly by the server. Let's say I "remove" a data from the list. The server should remove this data from the list of other people and without refreshing. "Your remote data source record count has changed, reloading from the first record." Error is very bad for me. because it would be sad to get such an error while updating in the middle of a data of 50 thousand rows. In this case, the absence of paging on the grid may cause you to have a crisis. :) I always look at the server logic, sorry as a backend. I want to share my web socket method.


```
connection.on("RecordDeleted", (myinternethatlaridto) => {
            let mrecid = myinternethatlaridto.recid
            let grid = w2ui.grid1
            //for grid
            if (w2utils.isInt(mrecid)) {
                if (grid) {
                    grid.remove(mrecid)
                }
            }
            //for form
            if (w2popup.status === "open") {
                let form = w2ui.form
                if (form) {
                    let frecid = form.recid
                    if (w2utils.isInt(frecid)) {
                        if (form.recid === mrecid) {
                            w2popup.close()
                            w2alert('Form closed. This is data another user deleted.')
                        }
                    }
                }
            }
            console.log("RecordDeleted")
        })
```

**Comment by vitmalina** [comment]
Synchronized updates is not implemented by grid default behavior. And it is not that straightforward to implement. What you can do is this
- do not set grid.url
- implemented you own mechanism via websockets to sync data
- if grid.url is not set, popups you mentioend will not be a problem.

If you you do set grid.url, you can still add onRequest, onLoad, etc events and implement your own logic.

This is the best I can offer right now. The review on grid pulling data will come later on, but there will unlikely be any substantial changes in current logic how it pulls data.
