### ISSUE TITLE
how to insert custom DOM into w2ui

### ISSUE THREAD

**Issue by trusktr** [vitmalina/w2ui#2314]
Hello Vitali! The docs [hint](https://w2ui.com/web/demos/#/combo/14) at making custom components. Wondering if you can show some snippets here about how to insert custom DOM into the w2ui.

What would be the recommended pattern for making a grid then putting any DOM in the layout? Or for example, how would I use a custom `<input>` or `<cool-input>` inside of a `form: {}`?

**Comment by trusktr** [comment]
These lines have hard-coded `<input`:

https://github.com/vitmalina/w2ui/blob/master/src/w2form.js#L1236-L1245

Maybe `form: {}` needs an option to tell it what element name to use, or perhaps a way to pass an element instance as alternative, and as long as that element implements the same API as `<input>` it should just work.

**Comment by vitmalina** [comment]
Joe! my friend, good to see you here. Well, w2form implements a variety of different types of controls out of the box. Here is the demo with a sampling of different control types https://w2ui.com/web/demos/#/form/3. It is quite useful. However, if you want to implement a completely custom control, you could use `type: 'html'` and just provide html code of your own control. Also, form will add events to controls so that it can listen to onchange, etc, and then update `form.record` when needed. The best way to do it is in `onRefresh` event in `event.done()` call back. See https://w2ui.com/web/docs/2.0/utils/events

As for the hint you mentioned, it is a hint to create new types of controls similar to w2form or w2toolbar. All of the controls, such as w2grid, w2toolbar, ect. inherit from w2base class. 

Also, if you want to add something into the grid cell, the easiest way would be to use cell renderer. Then you can just pass html you want to have in the grid. See renderer here https://w2ui.com/web/docs/2.0/w2grid.columns, see demo here https://w2ui.com/web/demos/#/grid/23

I hope this helps. Let me know if there is anything else I can help you with.

**Comment by vitmalina** [comment]
Closing the issue as it was more a question then a bug

**Comment by trusktr** [comment]
Thanks Vitali, nice to see you here too! That's nice that we can place custom content in there. It is good enough to get our custom elements in there. 

I tried this, https://jsfiddle.net/k4ojLfen, and I noticed a few things:

- it doesn't allow to return DOM nodes, which could be useful for using any APIs that may return actual DOM node references
- it re-runs every time (f.e. on sort) which means any returned HTML strings create new DOM each time iiuc (perf cost)
- doesn't give us a ref to the container. it could, for example, give us the ref to the cell element each time (can be the same ref if it only moved around)

Having refs to the container or accepting DOM return values could open up doors to easier integrations with external tools. 

As an example, we could use [`lit-html`](https://github.com/lit/lit/tree/main/packages/lit-html#overview), [solid's `html`](https://github.com/solidjs/solid/tree/main/packages/solid/html), [React's `ReactDOM.createRoot`](https://reactjs.org/docs/hello-world.html), etc, to render directly into containers:

```js
import {html} from 'lit-html'

function CellComponent(extra) {
    return html`
         <cool-element ...>${extra.value}</cool-element>
    `
}

let grid = new w2grid({
    // ...
            render: function (record, extra, el) {
                render(CellComponent(extra), el)
            },
    // ...
})
```
or

```jsx
            render: function (record, extra, el) {
                ReactDOM.createRoot(el).render(() => <cool-element />)
            },
```

etc.

And the beauty of this is that, as long as `el` is the same reference to a cell container (which should be the case if the cell only moved around) then these APIs will smartly re-use the same `<cool-element>` on each update instead of making a new one each time.
