### ISSUE TITLE
w2form float field type is not consistent

### ISSUE THREAD

**Issue by dv1x3r** [vitmalina/w2ui#2551]
## Short description
This is a small brother of issue #2549 
w2form float field type is not consistent (string when whole number is entered)

## What is current behaviour

w2form stores float value as a string when user enters the whole number:

<img width="497" alt="image" src="https://github.com/user-attachments/assets/d61b34c1-1c70-4851-b1c9-cb812772d182">

In case of decimals it works ok now:

<img width="498" alt="image" src="https://github.com/user-attachments/assets/34307569-5168-4a50-ac56-56cc1a08523f">

In case of garbage input it clears the field, but keeps the data:

<img width="499" alt="image" src="https://github.com/user-attachments/assets/d6c5e359-5c32-4f05-87a8-8417ac296123">

## What is desired behaviour

Float field should always be numeric or null (empty string is also ok, but not perfect).
Test cases: 0; 0.5; 0.50; 0.05; 15; 15.5... 

## Link to jsfiddle with sample code
https://jsfiddle.net/ek215nup/

## Steps to reproduce or sample

1. Create a w2form with a float field
2. Submit the form / check the record json content

I will play around with it this weekend, and maybe come up with a suggestion for a PR.
I think it could be handled in the same or similar way as the w2grid inline edit (which works perfectly there).

<img width="499" alt="image" src="https://github.com/user-attachments/assets/a7166d57-01a9-43f1-a715-a428dd4b882e">

**Comment by WillTheFarmer** [comment]
@dv1x3r I duplicated your fiddle code in a local w2ui-starter-es6 clone. The float field works properly with w2ui.es6.min.js:
/* w2ui 2.0.x (nightly) (4/26/2023, 11:04:17 AM) (c) http://w2ui.com, vitmalina@gmail.com */
When I change the import lines in main.js and start.js to point to 'https://rawgit.com/vitmalina/w2ui/master/dist/w2ui.es6.min.js' I get the same results as your fiddle.

The problem is in that file. The problem does not exist in w2ui-starter-es6 repository file.
![Screenshot 2024-08-25 001038](https://github.com/user-attachments/assets/9a26b09d-be7c-4c83-9270-f9204691128d)

**Comment by WillTheFarmer** [comment]
Hello @dv1x3r I do understand that. My point was something changed in newest version since the starter version. I'll figure it out and post the fix tonight. I am updating my app to newest w2ui version this afternoon. Last night I saw your post and since I use many FLOAT columns and fields in my app I looked into it. My post was as far as I got last night. I had to get to bed for farm work this morning. We built 500 feet high tensile fence now I am getting back to my desk for second shift.

**Comment by dv1x3r** [comment]
@WillTheFarmer ah, ok! Yes, the main difference could be related to #2549, and changes pushed one week ago. Initially it was just impossible to input "0.05" to the float field. I will also take a look today/tomorrow.

**Comment by dv1x3r** [comment]
Hi @WillTheFarmer , FYI, I just pushed my changes to my fork and made a PR #2552
The cleaning occurs only during the `change` event, after the user has fully completed their input.
Here is a new fiddle based on my fork if you would like to test it :)
https://jsfiddle.net/7aswxcyq/

**Comment by WillTheFarmer** [comment]
Hello @dv1x3r,
Thank you for getting this done and it works great in my app! I did start on this but got sidetracked on another issue. Now I am running on the latest version and everything works. Cheers Den! I owe you one.
