### ISSUE TITLE
Multi-popups fix!?

### ISSUE THREAD

**Issue by mehdi-cit** [vitmalina/w2ui#671]
Hello!
I've been looking into w2ui, started by checking the popup and seeing whether I can tweak it to fit my requirements. 
exp here: http://jsfiddle.net/9yegjn7g/
As you can see it was quite simple to add "a minimize to header only" functionality.
I found out however that one cannot have more than one popup at a time. I checked the code and it's indeed using a hard-coded id for the single popup. My question is that do you think it'd be too hard to change the code to allow for multiple popups to exist in the same page. For someone who's not familiar with w2ui and its code, would that take considerable time (more than an hour?).
If it's not straightforward, would the creator of w2ui consider implementing this? Any future plans.
Thanks a million.

**Comment by ratones** [comment]
Not sure if this îs stil active, but i thought I should post here.
I also had this request from our client and since I'm not in favor of using to many plugins I forked the project and added a new widget based on w2popup. It is still a work in progress, but so far I have the following working(not very well tested, tough):
- minimize functionality(windows are stacked at the bottom of the page)
- multiple windows. 
- content based on an element In page or passed as jquery object. If the element exist on page, it will not be copied , but moved entirely to the window content. Also, if "preserveContent" option is set, on close, the element will be put back in its original place. 
- on minimize and maximized, the window will preserve its location.
- window can be maximized from task bar. 

I would like to add manual resize option, I hope I'll have some time in the next days. 

If anyone still interested, I will push the current stage into the forked repository.

**Comment by siyadahmed** [comment]
> I would like to add manual resize option, I hope I'll have some time in the next days.
> 
> If anyone still interested, I will push the current stage into the forked repository.
> 
Hi Ratone,

What is the status of this fork. I can see it in your GIT. Is it still work in progress or completed?

Thnaks,
