### ISSUE TITLE
Compatibility with browserify

### ISSUE THREAD

**Issue by TomKaltz** [vitmalina/w2ui#712]
Can anyone shed any light on this?

**Comment by djulien** [comment]
I was able to get it working using the following code:

```javascript
var $ = require('jquery'); //npm copy (installed via "npm install jquery"), not CDN copy
global.jQuery = global.$ = $; //kludge: w2ui wants global jQuery and $
var w2ui_top = require("../lib/w2ui/w2ui-1.4.2.js"); //use explicit path (load via package.json no worky)
$ = global.$; //kludge: w2ui attachedto global.$, not $, so propagate back to my local copy
```

I also had to add one line to the end of w2ui-1.4.2.js:
```javascript
if (module) module.exports = {w2ui: w2ui, w2obj: w2obj, w2utils: w2utils}; //export top-level objects to commonjs
```
(I realize this is an old-ish post, but might help someone else who is also having this problem)

**Comment by BBE78** [comment]
@chalchis could you please send us your config with w2ui please? It becomes a nightmare to me...
Thx !

**Comment by pranavk** [comment]
As mentioned by @djulien a single line,

> if (module) module.exports = {w2ui: w2ui, w2obj: w2obj, w2utils: w2utils};

would be awesome to have.

@vitmalina Current approach though works in browser environments (as w2ui, w2obj are global variables and they automatically attach themselves to window instance), but these global variables are not exposed when we use w2ui.js as a *module*. For w2ui to be able to work with browserify we first need to ensure that w2ui behaves like an ideal js module (which it doesn't as it do not export its global variables using module.exports). For eg: if with current w2ui code, we do following

> var w2ui = require('w2ui');

we get nothing, because w2ui doesn't export anything.

**Comment by kupuguy** [comment]
Having found my way to this bug because I'm trying to load w2ui with webpack, I'll add the webpack workaround (this is for webpack2). As @djulien and @pranavk say we need to add a line to export the variables, but webpack has a means to do this automatically by using the exports-loader.

In webpack.config.js add this to the `rules` section:
```
        {
            test: require.resolve('w2ui'),
            use: [{ loader: 'exports-loader', options: 'w2ui,w2obj,w2utils' }]
        }
```
and now you can import `w2ui` just like any other module:
```
        import { w2ui, w2obj, w2utils } from 'w2ui';
```
Note that this still requires jQuery to be either loaded as a global or injected into w2ui using the imports-loader.

**Comment by balkarov** [comment]
@kupuguy hello. Thank you for your help.
But I have new problem. When I hover to button I get error: `$ is not defined`
But jQuery I resolve with ProvidePlugin and everywhere works.
When I click to button I get error  `w2ui is not defined`

My code
```
$("#va-content").w2layout({
            name: "layout",
            padding: 0,
            panels: [
                {
                    type: "bottom",
                    size: toolbarHeight,
                    style: pstyle,
                    content:
                        {
                            render: function () {
                                var container = $("#code-editor").detach();
                                $(this.box).append(container);
                            }
                        },
                    toolbar: {
                        name: "toolbar",
                        style: "border-top: 1px solid silver",
                        items: [
                            {
                                type: "button",
                                id: "zoom",
                                icon: "fa fa-search-plus",
                            }
                        ]
                    }
                }
            ]
        });
```

**Comment by caracal7** [comment]
@balkarov I have the same problem(

**Comment by balkarov** [comment]
@caracal7 this problem because w2ui use functions from  w2ui and jQuery in html (you can see in html onclick, onmouseover and etc).
I temporary resolved my problem with dirty hack. I bind jQuery and w2ui to window:
```
window.w2ui = require(“w2ui”);
window.$ = require(“jquery”);
```

**Comment by caracal7** [comment]
@balkarov, thanks) 
I already solved it by the same way.

But any modules in global scope it's very bad practice. And I don't like jQuery at all and especially in global scope but I must include it with w2ui((((

**Comment by balkarov** [comment]
@caracal7 yes, I know. Because it is dirty hack. 
If you find another method inform me here please
