### ISSUE TITLE
On grid, row previosly selected and checked after search are selected but not checked

### ISSUE THREAD

**Issue by FilippoBenassutiCDM** [vitmalina/w2ui#766]
I'm working with a grid the pull data from server.
I enabled the selectColumn on config so rows have a checkbox at the first column.

When i select all fields or some fields and then i made a search I expect that rows that match the search are show with the checkbox selected if them was previously selected.

But I see row selected with light blue and the checkbox is not checked.

My problems comes with the need to keep track of records previosly selected cross multiple select.

**Comment by noup** [comment]
Hi! As a suggestion, maybe this could be implemented as an option? I believe there are 2 possible functional behaviors here:
1) The user is managing visible records - this is the current implementation, selection is reset on search and only applies to visible records.
2) The user is managing the total list of records - searching is necessary to find specific records in order to select them, so it would be nice to keep the selection when searching.

Our case: we are showing a w2grid with thousands of records, all selected by default (a selected record means it's enabled/usable in our application). Because the number of records is large, if the user wants to unselect a specific record, searching is required. However, search() clears the current selection. Doing getSelection() and then reselecting after a search doesn't perform well in our case, as the user sees search results appearing unselected and then take 2 seconds to become selected.

We are currently getting around this by changing line :4467 in the latest 1.5.x nightly build, though we're not sure of its further implications:
-this.last.selection.indexes = [];
+this.last.selection.indexes = this.getSelection();

**Comment by vitmalina** [comment]
I have had similar business requirement and the best implementation seems to be by implementing 2 grids. One with available records another one with selected. If you put them side by side, on the left user can search and dbl click to move it to the right. This present less confusion for the end user as he always knows what is selected. 

Alternatively, you can create an input control with multi select options, see http://w2ui.com/web/docs/form/fields-enum as a demo. However, this only works if you list data has one or few columns.
