### ISSUE TITLE
set value to field drop down list

### ISSUE THREAD

**Issue by ylyxf** [vitmalina/w2ui#798]
in the page of http://w2ui.com/web/demos/#!fields/fields-3
i want to set the default value when the form is loaded.
i change the line 14 like this : `<input type="list" value="John Adams">` .
but it does not work.
is there any method to set the default value ?

**Comment by mpf82** [comment]
I think the "problem" with lists is, that internally they use an object in the form
{ text: "John Adams", id: "John Adams" }

Since we are setting the default value in the code, we've handled this internally with the following code snippet:

if(field.type == "list") {
   if(typeof(record[field.name]) == 'string') {
       record[field.name] = {text: record[field.name], id: record[field.name]};
   }
}

I'm not sure if you can pass an object in the HTML declaration, but what happens if you write:

<input type="list" value='{ text: "John Adams", id: "John Adams" }'>

Note the different quotation marks!

If it does not work, you could also try to set the default value with Javascript and pass an object instead of a string, as described above.

Hope that helps,
Mike

**Comment by vitmalina** [comment]
Please post your questions to w2ui.com in comments section or on stackoverflow.com. Please submit only bugs here.
