### ISSUE TITLE
w2grid expandable rows are broken

### ISSUE THREAD

**Issue by agzamovr** [vitmalina/w2ui#804]
In last versions of library w2grid expandable rows are broken. There are extra space in subgrid and plus signs for expanding are in wrong position. If enable line numbers column then extra space in sub grid becomes even bigger.
![image](https://cloud.githubusercontent.com/assets/957935/5991417/e5a1a9b6-aa0f-11e4-9b7e-d5ddb02a8317.png)

**Comment by agzamovr** [comment]
I found that this bug is introduced by b99d945c21080cd5b72f79bb9d6b225fe0a8c292  merge commit

**Comment by vitmalina** [comment]
Yes. Frozen columns have cause a problem here. I will look into it. Also, in the future release the subgrids will be refactored and the functionality will change. I do not like how current subgrids works and will be refactoring it quite a bit in the next month.

**Comment by SouXin** [comment]
First of all thanks for this great library. Simple, lite and powerful. 
If you will keep to support it it would be great. 
And BTW did you look at this issues (with frozen columns)?
Because I think there is another one which maybe related. 
When you expand the grid spinner continuously working.  And since opacity attribute is  0. Information is not shown. Rough fix is: 
```javascript
// fix not shown values
$('#' + ev.box_id).css('opacity', '1');
```
But spinner is still working.

Another issue is not shown scroll bar in the inner grid with rough fix.
```javascript
 // fix the scroll within the result
 var intOverSize = $('#grid_modelsRelatedToVendor_records')[0].scrollHeight;
 if (intOverSize > 660) {
      $('#grid_modelsRelatedToVendor_records').removeAttr('style');
       $('#grid_modelsRelatedToVendor_records').css({ 'top': '26px', 'overflow-x': 'hidden', 'overflow-y': 'auto' });
 }
```

But anyway great job. Very appreciated.

**Comment by adilek** [comment]
Hello, 
I have solved this problem. Details in https://github.com/vitmalina/w2ui/pull/1013

The problem was that the frecords is in seperate div so they are not in the same table row.

**Comment by adilek** [comment]
This issue can be considered as "closed". The bug is fixed in recent commit.
