### ISSUE TITLE
1.5 version has a problem with diffrent width look at pic

### ISSUE THREAD

**Issue by i900916** [vitmalina/w2ui#829]
![qq 20150302225951](https://cloud.githubusercontent.com/assets/1784357/6443166/0bd5146a-c130-11e4-88b4-3569861681f1.png)

**Comment by vitmalina** [comment]
Acknowledged

**Comment by mpf82** [comment]
Seems to be fixed in the latest JS and CSS.

Datetime with ``between`` is obviously still wider than all other fields, but no biggie in my book.

![2017-11-02 21_38_01-web template - v1 1](https://user-images.githubusercontent.com/10152404/32349088-35d95234-c016-11e7-8b4a-3c3d2e46b2d7.png)

@mrg2001 this can probably be closed

**Comment by mpf82** [comment]
Closing this issue, as it seems to be fixed in the latest version.
