### ISSUE TITLE
Drop-down list bug

### ISSUE THREAD

**Issue by ppearson111** [vitmalina/w2ui#850]
Love the w2ui and have worked quite a bit with it at this point... this may be a bug... I have 2 drop-down lists in the jquery tab control -- when the page loads, if the tab containing the drop-down lists is the initial active tab, then the drop-downs draw correctly.  However, if I switch tabs and then switch back to the tab containing the drop-downs, the drop-down "down arrow" is drawn outside the control.  This appears to be a bug... or is there something else I'm missing?  thanks!
(by the way, I'm currrently running the 1.5.x version (snapshot from github on 3/16/2015)

![drop-down-bug](https://cloud.githubusercontent.com/assets/91089/6831090/c8e98594-d2e3-11e4-900d-8b8ec091fab6.png)

**Comment by vitmalina** [comment]
This happens because initially the drop down was in a hidden container and then you displayed it. You should either (1) refresh fields when they are visible, or if their width/height changes or (2) init fields when they are shown. To init field you need to call $().w2field(...) command again, but to refresh you can just use
```
$('#id').w2field().refresh();
```
Works only with 1.5 branch.

**Comment by vitmalina** [comment]
I assume it worked.
