### ISSUE TITLE
Defect report of version 1.5

### ISSUE THREAD

**Issue by xghost19** [vitmalina/w2ui#852]
Hi vitmalina.
I appreciate for w2ui 1.42 helps my work well.

I downloaded 1.5. the bug "date type fields calendar always return 1970-01-01" is fixed. Thank you.

But,there are new bugs in 1.5.
- grid data copy and paste(onCopy event not work) doesn't work...
- w2confirm popup buttons doesn't show correctly...
- [reset and search] buttons on grid search window doesn't show correctly...
I have noticed the fact that.

Working with Google Chrome...

The above was just a quick report.

With best regards!

**Comment by vitmalina** [comment]
1.5.x is currently considered unstable, but the problems you describe are not presenting in my builds. If you are evaluating it so that you can more from 1.4.2 because of date bug, see, if latest bug fixes in 1.4.x branch fixed your problems.

https://raw.githubusercontent.com/vitmalina/w2ui/w2ui-1.4/dist/w2ui.js
https://raw.githubusercontent.com/vitmalina/w2ui/w2ui-1.4/dist/w2ui.css

**Comment by vitmalina** [comment]
If there ane no other comments I am going to close this issue.
