### ISSUE TITLE
CSS Stylesheet not recognized as needed dependency by wiredep

### ISSUE THREAD

**Issue by bbottema** [vitmalina/w2ui#860]
I'm using [grunt wiredep](https://github.com/stephenplusplus/grunt-wiredep) to manage my css/script dependencies in my index.html. Though it is injecting w2ui.js properly, the CSS file is ignored.

``` html
<!-- bower:css -->
... bower/w2ui/w2ui-1.4.2.min.css missing ...
<!-- endbower -->

<!-- bower:js -->
<script src="bower/w2ui/w2ui-1.4.2.min.js"></script>
<!-- endbower -->
```

I don't know how these dependencies should be marked, but is it possible you're missing a hint in your bower config?

Here's a [hint by the developer of wiredep](https://github.com/taptapship/wiredep#user-content-what-can-go-wrong):

> - A Bower package may not properly list its dependencies in its bower.json file.
> - A Bower package may not specify a main property in its bower.json file.
> 
> In both of these cases, it is most helpful to send a PR to the offending repository with a solution. 

In the bower-retrieved package of w2ui, the bower.json file is missing the css in its main property:

``` javascript
{
    "name"        : "w2ui",
    "version"     : "1.4.2",
    "homepage"    : "http://w2ui.com",
    "main"        : "w2ui-1.4.2.min.js",
    "ignore"      : ["bower.json"],
    "author": {
        "name"  : "Vitali Malinouski",
        "url"   : "http://w2ui.com",
        "email" : "vitmalina@gmail.com"
    }
}
```

**Comment by vitmalina** [comment]
If I add w2ui repository to bower, it will download it in its entirety. With all the tests, docs, and other unnecessary files. I do not like that, as I want my sources clean and w2ui distribution is only 2 files (js and css). Because of this I have created repository for bower distribution. See https://github.com/vitmalina/w2ui-dist, where there is proper bower file.

Please close this issue if this answers your questions.

**Comment by mpf82** [comment]
Closing issue: no response
