### ISSUE TITLE
Unselect event on arrow up/down does not include recid

### ISSUE THREAD

**Issue by deployable** [vitmalina/w2ui#902]
I run functions relating to a record on the select/unselect events. This works fine when the mouse is used to select. 

When the keyboard arrows are used (up/down) the unselect event that fires has no `recid` is attached.  

      w2ui['the_grid'].on 'unselect', (ev)->
        debug_grid ev.recid, JSON.stringify(ev, null, 2)

Mouseclick:

    555de947045d893f4fde90ec {
      "type": "unselect",
      "execute": "before",
      "target": "the_grid",
      "onComplete": null,
      "phase": "before",
      "recid": "555de947045d893f4fde90ec",
      "index": 8,
      "isStopped": false,
      "isCancelled": false
    }

Keypress:

    undefined {
      "type": "unselect",
      "execute": "before",
      "target": "the_grid",
      "onComplete": null,
      "phase": "before",
      "all": true,
      "isStopped": false,
      "isCancelled": false
    }

It looks like the `selectNone()` function is used due to `all: true` being in the `unselect` event. 

Is there any reason why the individual unselects are not fired in the `selectNone` loop? 
Is there a reason keypress uses `selectNone()` instead of `unselect`? A mouse click from multiple previous selects fires `unselect` for each record.
Another alternative would be that `selectNone` dumps the array of recids that were selected.

**Comment by vitmalina** [comment]
Good catch. I have fixed it in both master and 1.4 branch. If you use 1.4 branch, download latest form /dist folder.

Also, if you have more then 300 selected, then selecting next record will call selectNone(), not unselect(). This is due to speed issues. If you have 100k records selected and then click on, it will be extreemly slow to sent 100k unselect events, so it sends one, which is selectNone();

**Comment by deployable** [comment]
Thank for the quick fix and the note, I will add a check for the 300.
