### ISSUE TITLE
Standalone (grid) search functionality and UI ?

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#914]
Is it possible to use the Grid Search in standalone mode?, i.e. without displaying and loading data into the grid: just the button/popup and the save to trigger a request with the same parameters? like it would do when used with the grid?

This would allow it's reuse in many more scenarios, e.g. charts that need a pre-filtering, Excel reports that need a pre-filtering, PDF reports that need pre-filtering, etc.

Thank you.

**Comment by vitmalina** [comment]
Will think about it. For now, you can create overlays with custom forms and then add them as buttons to grid's toolbar or anywhere else. It is relatively easy to do. I do not think that this is something that can be frequently used, hence, I am not sure it is worth implementing as part of the grid. There are more pressing features.

**Comment by hansgru** [comment]
> For now, you can create overlays with custom forms

It's not that much about the reuse of the UI rendered, but about using the same "connector" (since w2ui seems to require one) as for the grid and having a consistent query API.

**Comment by aadrian** [comment]
+1 for a reusable search component if it does not conflict with the planned road-map.

I don't think it's trivial to make a reusable custom search panel since the GUI needs to change depending of the field type and the selected operation and allowed values, and there's also the entire server side handling of so many various parameters.

We use quite successfully this component: http://mistic100.github.io/jQuery-QueryBuilder/
since it can support grouping/nesting of logic for the scenarios that require it.
It would be cool if the W2UI search panel would adopt this "dynamic" rendering strategy.

**Comment by vitmalina** [comment]
I will put it on the road map
