### ISSUE TITLE
Offline version of docs

### ISSUE THREAD

**Issue by hansgru** [vitmalina/w2ui#960]
Please update the docs to work offline.
There still are some of the files that reference CDN.

Thank you.

**Comment by vitmalina** [comment]
It is not true. I have turned off my wi-fi and opened both /docs and /demos folder and all worked fine. THe only demo that did not work was infinite scroll, which requires remote data source and cannot work off line. But it is one demo from like 100 of them. 

There are some references to w2ui.com, but they are replaced with JS. It is there because these same demos/docs work on w2ui.com and there I need to pass to jsfiddle.com to make it work. 

If you find something that does not work, please provide more details.

**Comment by hansgru** [comment]
Several examples in the docs seem to reference CDN (not local) :
https://github.com/vitmalina/w2ui/blob/master/docs/overview/form.html
https://github.com/vitmalina/w2ui/blob/master/docs/overview/grid.html
https://github.com/vitmalina/w2ui/blob/master/docs/overview/layout.html
https://github.com/vitmalina/w2ui/blob/master/docs/overview/sidebar.html
https://github.com/vitmalina/w2ui/blob/master/docs/overview/tabs.html
https://github.com/vitmalina/w2ui/blob/master/docs/overview/toolbar.html

**Comment by vitmalina** [comment]
As you can see, the linking is in a textarea, it is merely and example of the usage.
