### ISSUE TITLE
Local Json file in W2UI grid

### ISSUE THREAD

**Issue by rajb21** [vitmalina/w2ui#976]
How to access local Jason file in W2UI grid?
for eaxmple : F:\json\test.json

w2ui['grid'].load('F:\json\test.json'); is not working for me.

Thank you in advance.

**Comment by aadrian** [comment]
> How to access local Jason file in W2UI grid?

I think It's not possible because the browser can't perform an AJAX request offline, on the local file system (using the file protocol). For this you need a to start a local web server (it's trivial, see below) and serve the JSON file's content from there.

Some simple ways to start a quick and simple local web server:
 - Python SimpleHTTPServer: http://www.pythonforbeginners.com/modules-in-python/how-to-use-simplehttpserver/
 - NodeJS : https://www.npmjs.com/package/http-server
 - Ruby: http://stackoverflow.com/questions/3108395/serve-current-directory-from-command-line
 - Groovy: https://gist.github.com/iamnoah/9393655

You can find this kind of "simple http server" for almost all languages.

**Comment by rajb21** [comment]
Thank you for the help :)

**Comment by TrevorPT** [comment]
You can also embed w2ui in a nw.js (node-webkit) application which supports ajax and local file system access.  nw.js is both the server and the client (browser).

Official site: http://nwjs.io/
github: https://github.com/nwjs/nw.js#node-webkit-is-renamed-nwjs

**Comment by rajb21** [comment]
Thank you for your help :)

**Comment by vitmalina** [comment]
I hope the issue is resolved, open it back if not.
